vacations:
  application:
    ui:
      title: Balance de vacaciones
      resource: classpath:\vacations-ui.fxml

app:
  config:
    location: ${java.io.tmpdir}vacations-balance\config.json
