vacations:
  application:
    ui:
      title: Balance de vacaciones
      resource: classpath:\vacations-ui.fxml

app:
  config:
    location: ${java.io.tmpdir}vacations-balance\config.json

error:
  messages:
    load-json-internal: No se pudo cargar archivo interno
    load-json-file: No se pudo cargar archivo
    write-json-file: No se pudo escribir archivo
    create-dirs: No se pudieron crear directorios
    property-not-found: Propiedad no encontrada
    invalid-data-type: Tipo de valor inv√°lido
    read-balance-file: No se pudo leer archivo de balance de vacaciones
    balance-not-found: Balance no encontrado para empleado

logging:
  level:
    root: INFO
    com:
      legadi: DEBUG