vacations:
  application:
    ui:
      title: Balance de vacaciones
      resource: classpath:\vacations-ui.fxml

app:
  config:
    location: ${java.io.tmpdir}vacations-balance\config.json
    backup:
      location: ./respaldo
      tag:
        format: yyyyMMdd-HHmmss-SSS
  date:
    formats: dd/MM/yyyy, MM/dd/yyyy, yyyy/MM/dd, dd-MM-yyyy, MM-dd-yyyy, yyyy-MM-dd

alert:
  messages:
    load-json-internal: 'No se pudo cargar archivo interno: %s'
    load-json-file: 'No se pudo cargar archivo: %s'
    write-json-file: 'No se pudo escribir archivo: %s'
    create-dirs: 'No se pudieron crear directorios: %s'
    property-not-found: 'Propiedad no encontrada: %s'
    invalid-data-type: 'Tipo de valor inválido, esperado[%s]: %s'
    read-balance-file: 'No se pudo leer archivo de balance de vacaciones: %s'
    write-balance-file: 'No se pudo guardar archivo de balance de vacaciones: %s'
    balance-not-found: 'Balance no encontrado para empleado: %s'
    employee-saved: 'Balance de empleado "%s" guardado correctamente'
    year-not-registered: 'Año no registrado para aniversario: %s'
    unable-to-backup: 'No se pudo generar respaldo: %s'

component:
  texts:
    employee-name-first-cell-help: Celda inicial de empleado
    total-taken-days-column-help: Columna de días tomados
    company-name-cell-help: Celda de empresa
    start-date-cell-help: Celda de fecha inicial
    balance-days-cell-help: Celda de balance de días
    previous-vacations-days-cell-help: Celda de días de vacaciones previos
    ratio-days-cell-help: Celda de proporción de días
    allowed-days-year-first-cell-help: Celda inicial de año
    allowed-days-value-column-help: Columna de días
    allowed-days-value-row-help: Fila de días
    accept-button: Aceptar

logging:
  level:
    root: INFO
    com:
      legadi: DEBUG